### ISSUE TITLE
GAMLSS implementation

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#125]
The current calculations using the Cole LMS method is vulnerable in certain circumstances where the GAMLSS method might be more appropriate. We should implement both methods of SDS and centile calculation and compare.

**Comment by statist7** [comment]
I've been provisionally updating my code to include the GAMLSS adjustment, but I've realised it is a can of worms.

The problem is that it alters the relationship between z-score and centile, and means for example that a measurement on the median for age has a z-score that is not exactly zero. This troubles me!

Also, in my testing I tried to get the same answer from the GAMLSS code and my own, but it involves specifying the z-score and/or the centile, but they have different meanings so they don't agree. 

I've checked to see the size of the discrepancy using all the measurements in the uk90 reference, including all the ages in the two sexes, a total of 3990 distinct data rows. It turns out that for three-quarters of them the discrepancy if I make the change is zero, which is reassuring.

The size of the discrepancy depends on the z-score, but in the extreme case of z = -3 for boys triceps skinfold at age 9 where L is -1.43 (i.e. very negative) and S is 0.197 (i.e. large), the change in code alters the centile by 0.4%. This seems small to me.

I'm wondering if we shouldn't make the change, as it complicates things in unexpected ways, and the effect on the centiles is minimal. 

What do you think?

I do hope you haven't been beavering away at it over the weekend...

**Comment by statist7** [comment]
Further to the above, I've checked to see by how much the z-score changes using the different definition.

It depends on the values of L and S (not M), and is largest for large negative z. Based on the 3990 rows in the UK90 the largest absolute discrepancies in z-score are:
          z = -3                  z = -2                  z = -1                     z = 0                    z = 1                    z = 2                    z = 3
Max.   :0.04   Max.   :3.5e-03   Max.   :6.7e-04   Max.   :2.4e-04   Max.   :1.3e-04   Max.   :8.1e-05   Max.   :5.8e-05

I think we can live with these. z = -3 is the 0.1th centile and it is the most extreme example in UK90.

We can document it by saying we have decided not to apply the GAMLSS adjustment, as it complicates the relationship between M, z and centile, and in any case it is a very small adjustment in most cases.

**Comment by pacharanero** [comment]
Sounds reasonable. These are my favourite kinds of issues - one we can close after a hefty statistical discussion which I barely understood :rofl:

**Comment by eatyourpeas** [comment]
I agree. And in clinical practice in fact it is actually quite common to see z scores of -6 or +6 when talking about weight or BMI, . I will leave the code in for posterity (the two new methods are ```gamlss_measurement_for_z``` and ```gamlss_z_for_measurement``` in ```global_functions.py```.) though it has not yet been tested.

**Comment by eatyourpeas** [comment]
Just for the sake of documentation: as we are not implementing these functions I will not publish to production but leave the [branch](https://github.com/rcpch/digital-growth-charts-server/tree/gamlss) for posterity. Please note to users wishing to implement the GAMLSS methods they have not been tested or validated. They are harder to implement because they involve calculating SDS, then centile, making GAMLSS adjustment and then converting back to SDS, and then again to centile.
