### ISSUE TITLE
API Returned 500 Status Code

### ISSUE THREAD

**Issue by snield1150** [rcpch/digital-growth-charts-server#192]
This morning, Monday 22/05/23 around 9am to 11am, we were doing some testing on our application and were getting back a 500 Internal Server error from the https://api.rcpch.ac.uk/growth/v1/uk-who/calculation end point.

When we tested again about 12pm, it was working OK and has been since.

We are wondering what might have been the cause, for future reference.

The error message appearing in our logs was:
**The SSL connection could not be established, see inner exception. System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid**

Thanks

**Comment by eatyourpeas** [comment]
Apologies Sarah the error was our end – we identified it and corrected it once aware.
I am sorry for any inconvenience, and there are now contingencies in place to prevent this happening again.
S


From: Sarah Nield ***@***.***>
Date: Monday, 22 May 2023 at 15:07
To: rcpch/digital-growth-charts-server ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rcpch/digital-growth-charts-server] API Returned 500 Status Code (Issue #192)

This morning, Monday 22/05/23 around 9am to 11am, we were doing some testing on our application and were getting back a 500 Internal Server error from the https://api.rcpch.ac.uk/growth/v1/uk-who/calculation end point.

When we tested again about 12pm, it was working OK and has been since.

We are wondering what might have been the cause, for future reference.

The error message appearing in our logs was:
The SSL connection could not be established, see inner exception. System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid

Thanks
