### ISSUE TITLE
Signup page is not working for the moment? 

### ISSUE THREAD

**Issue by tommyyama2020** [rcpch/digital-growth-charts-server#193]
I am not sure if it is appropriate to raise the issue here. But hope it works.

It seems that a signup completion email was not sent to my inbox and I was unable to login the portal as well when I was trying to get API keys by signing in . 

https://dev.rcpch.ac.uk/signup

**Comment by eatyourpeas** [comment]
Thanks for getting in touch
This is not really the place to post issues relating to access. We have resources [here](https://growth.rcpch.ac.uk/about/contact/) including a discussion forum and an email address.

**Comment by pacharanero** [comment]
@tommyyama2020 thanks for posting about the problem you are having. @eatyourpeas is right that this is not the correct repo to report issues with access to the API, but since we don't have a repo for the API Management platform at this stage, it's fair enough that you would raise here. I will investigate the email sending situation from the Azure API Management Platform, which is what we use internally for access to the API.

**Comment by pacharanero** [comment]
@tommyyama2020 I've tried to sign up today at the API Management portal (dev.rcpch.ac.uk) and it does seem to be working for me. The confirmation email did arrive, and was quite quick to arrive. The sender email was not correct though so I will raise an internal ticket to fix this. It may be worth checking spam in case it failed email verification and was flagged.
