### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#75]
https://github.com/rcpch/digital-growth-charts-server/blob/b9f948e00a94837f429b974e5f5c412ea521d2b9/app.py#L21-L21

**Comment by pacharanero** [comment]
The API Server no longer performs cross-origin requests. In the days when we were separating out the Flask client there might have been a period where the Flask Client needed to be able to call the API server. But the API server is completely self contained now, and doesn't call out to any other servers. So I think this can be closed, if you agree @eatyourpeas ?

The React client may still require CORS policy to be set so that it can call out to the server even though it are a browser based application. CORS only applies in the browser context, for security purposes.

A good resource on this that may help is: https://dev.to/matheusguimaraes/fast-way-to-enable-cors-in-flask-servers-42p0

**Comment by eatyourpeas** [comment]
CORS makes my head spin, like [Professor Brainstawm](https://www.amazon.co.uk/Incredible-Adventures-Professor-Branestawm/dp/1862307369). On my local machine I have to switch security off on the browser. But once deployed it works so I think we should close this.
